### ISSUE TITLE
arbitrary keys with validated value

### ISSUE THREAD

**Issue by Le0Developer** [mizchi/lizod#10]
How do you validate an object with arbitrary keys but known value?
eg:
```ts
let a: {[key: string]: number} = {
  a: 123,
  b: 456,
}
```
a & b can be arbitrary, but the value is always a `$number`.

`$object({}, false)` accepts arbitrary keys, but has no way to verify values.

**Comment by mizchi** [comment]
Ok, I will add `$record($string, $number)`

**Comment by mizchi** [comment]
@Le0Developer Hi, I finally added `$record` validator!

https://github.com/mizchi/lizod/blob/main/src/index.test.ts#L114-L133

**Comment by Le0Developer** [comment]
Thanks!
