### ISSUE TITLE
array with known shape

### ISSUE THREAD

**Issue by Le0Developer** [mizchi/lizod#11]
How do you validate an array with an exact known shape?
eg:
```ts
let a: [number, number, string] = [1, 2, "3"];
```
`$array($union([$number, $string]))` would also accept `[1, 2, 3]` or `["1", "2", 3]`.

Potentially (didn't test) `$object` could work as a workaround? But I'd prefer `$array([$number, $number, $string])` over `$object({0: $number, 1: $number, 2: $string})` (didn't test if this works)

**Comment by yudai-nkt** [comment]
It's missing in the README, but you can use `$tuple` added in #6.

**Comment by Le0Developer** [comment]
Thanks for the info!
