### ISSUE TITLE
Missing transform, default function and some basic validate like string().url(), string().email()...

### ISSUE THREAD

**Issue by nhattran998** [mizchi/lizod#8]
Hi Mizchi, could you share the way to use `z.string().transfrom().optional().default()` ? Thank you <3.

**Comment by mizchi** [comment]
transform() and default() have side effects on the input. This implementation is complicated and is essentially a post-process after validation, not validation itself.

We have chosen not to implement these to make the implementation lightweight and to encourage a better functional style.
